/**
 * Data layer for the Travel Journey component.
 * Single source of truth for the travel page.
 *
 * To add a new stop: append an entry to `travelStops`.
 * The page renders all stops dynamically — no hardcoded layout.
 */

export interface TravelStop {
  /** Unique slug (kebab-case) */
  id: string;
  /** City or location name */
  city: string;
  /** Country name */
  country: string;
  /** Flag emoji */
  flag: string;
  /** Optional human-readable date — "Jun 2024", "Summer 2023", etc. */
  date?: string;
  /** Path to hero image (relative to /public) */
  image: string;
  /** Emoji representing the vibe / activity of the stop */
  activity: string;
  /** Accessible label for the activity emoji */
  activityLabel: string;
  /** Short story or narrative snippet about the stay */
  description?: string;
  /** Key highlights or favorite spots */
  highlights?: string[];
  /** Geographic coordinates string (e.g. "12.9716° N, 77.5946° E") */
  coordinates?: string;
}

export const travelStops: TravelStop[] = [
  {
    id: "tioman",
    city: "Tioman Island",
    country: "Malaysia",
    flag: "🇲🇾",
    image: "/images/travel/tioman.jpg",
    activity: "🤿",
    activityLabel: "Scuba Diving",
    description: "Crystal-clear waters, vibrant coral reefs, and tranquil island vibes in the South China Sea.",
    highlights: ["Coral reef dive sites", "Sunset beach walks", "Secluded bays"],
    coordinates: "2.7904° N, 104.1654° E",
  },
  {
    id: "singapore",
    city: "Singapore",
    country: "Singapore",
    flag: "🇸🇬",
    image: "/images/travel/singapore.jpg",
    activity: "🏙️",
    activityLabel: "City Exploring",
    description: "A futuristic skyline seamlessly blended with lush tropical gardens and world-class street food.",
    highlights: ["Gardens by the Bay", "Hawker center feasts", "Marina skyline"],
    coordinates: "1.3521° N, 103.8198° E",
  },
  {
    id: "warsaw",
    city: "Warsaw",
    country: "Poland",
    flag: "🇵🇱",
    image: "/images/travel/warsaw.jpg",
    activity: "🚶",
    activityLabel: "Walking the Old Town",
    description: "A resilient city blending meticulously restored history with vibrant modern urban life.",
    highlights: ["Old Town Market Place", "Vistula River boulevards", "Fryderyk Chopin museum"],
    coordinates: "52.2297° N, 21.0122° E",
  },
  {
    id: "krakow",
    city: "Kraków",
    country: "Poland",
    flag: "🇵🇱",
    image: "/images/travel/krakow.jpg",
    activity: "🏰",
    activityLabel: "Historic Sites",
    description: "Cobblestone streets, royal castle towers, and century-old cafes steeped in rich medieval history.",
    highlights: ["Wawel Royal Castle", "Main Square (Rynek Główny)", "Kazimierz district"],
    coordinates: "50.0647° N, 19.9450° E",
  },
  {
    id: "budapest",
    city: "Budapest",
    country: "Hungary",
    flag: "🇭🇺",
    image: "/images/travel/budapest.jpg",
    activity: "♨️",
    activityLabel: "Thermal Baths",
    description: "The Pearl of the Danube with grand architecture, historic thermal baths, and legendary ruin bars.",
    highlights: ["Széchenyi Thermal Baths", "Parliament illumination", "Fisherman's Bastion"],
    coordinates: "47.4979° N, 19.0402° E",
  },
  {
    id: "prague",
    city: "Prague",
    country: "Czech Republic",
    flag: "🇨🇿",
    image: "/images/travel/prague.jpg",
    activity: "🍺",
    activityLabel: "Beer & Culture",
    description: "The City of a Hundred Spires — gothic bridges, red rooftop views, and bohemian atmosphere.",
    highlights: ["Charles Bridge at dawn", "Prague Castle", "Historic breweries"],
    coordinates: "50.0755° N, 14.4378° E",
  },
  {
    id: "frankfurt",
    city: "Frankfurt",
    country: "Germany",
    flag: "🇩🇪",
    image: "/images/travel/frankfurt.jpg",
    activity: "🏙️",
    activityLabel: "Skyline & Culture",
    description: "A dynamic contrast of modern financial skyscrapers and charming traditional timber-framed Römerberg buildings.",
    highlights: ["Römerberg Square", "Main River promenade", "Museums Riverbank"],
    coordinates: "50.1109° N, 8.6821° E",
  },
  {
    id: "cologne",
    city: "Cologne",
    country: "Germany",
    flag: "🇩🇪",
    image: "/images/travel/cologne.jpg",
    activity: "⛪",
    activityLabel: "Gothic Architecture",
    description: "Home to the awe-inspiring twin-spired Cologne Cathedral and vibrant Rhine-side culture.",
    highlights: ["Cologne Cathedral", "Hohenzollern Bridge", "Belgian Quarter"],
    coordinates: "50.9375° N, 6.9603° E",
  },
  {
    id: "barcelona",
    city: "Barcelona",
    country: "Spain",
    flag: "🇪🇸",
    image: "/images/travel/barcelona.jpg",
    activity: "🏖️",
    activityLabel: "Architecture & Coast",
    description: "Gaudí's surreal architectural masterpieces meet Mediterranean sea breezes and lively tapas culture.",
    highlights: ["Sagrada Família", "Park Güell", "Gothic Quarter alleys"],
    coordinates: "41.3879° N, 2.1699° E",
  },
  {
    id: "pamplona",
    city: "Pamplona",
    country: "Spain",
    flag: "🇪🇸",
    image: "/images/travel/pamplona.jpg",
    activity: "🐂",
    activityLabel: "Historic Citadel",
    description: "Famous for the historic running of the bulls, rich Basque gastronomy, and ancient city ramparts.",
    highlights: ["Plaza del Castillo", "Citadel Park", "Calle Estafeta"],
    coordinates: "42.8125° N, 1.6458° W",
  },
  {
    id: "san-sebastian",
    city: "San Sebastián",
    country: "Spain",
    flag: "🇪🇸",
    image: "/images/travel/san-sebastian.jpg",
    activity: "🍷",
    activityLabel: "Pintxos & Beaches",
    description: "A coastal paradise famed for La Concha bay and world-renowned pintxos bar hopping in the Old Town.",
    highlights: ["La Concha Beach", "Parte Vieja pintxos", "Monte Igueldo view"],
    coordinates: "43.3183° N, 1.9812° W",
  },
  {
    id: "vienna",
    city: "Vienna",
    country: "Austria",
    flag: "🇦🇹",
    image: "/images/travel/vienna.jpg",
    activity: "🎻",
    activityLabel: "Imperial Palaces",
    description: "Grand imperial palaces, classical music history, and elegant century-old coffeehouse culture.",
    highlights: ["Schönbrunn Palace", "St. Stephen's Cathedral", "Traditional coffeehouses"],
    coordinates: "48.2082° N, 16.3738° E",
  },
  {
    id: "bratislava",
    city: "Bratislava",
    country: "Slovakia",
    flag: "🇸🇰",
    image: "/images/travel/bratislava.jpg",
    activity: "🏰",
    activityLabel: "Danube Castle",
    description: "A charming capital dominated by Bratislava Castle overlooking the Danube and pedestrian-only Old Town.",
    highlights: ["Bratislava Castle", "Most SNP UFO tower", "Old Town hall square"],
    coordinates: "48.1486° N, 17.1077° E",
  },
  {
    id: "london",
    city: "London",
    country: "United Kingdom",
    flag: "🇬🇧",
    image: "/images/travel/london.jpg",
    activity: "🎡",
    activityLabel: "Global Metropolis",
    description: "Iconic landmarks, world-class theatre in the West End, expansive Royal Parks, and endless neighborhood discoveries.",
    highlights: ["Thames river walk", "Covent Garden & West End", "Hyde Park strolling"],
    coordinates: "51.5074° N, 0.1278° W",
  },
  {
    id: "bali",
    city: "Bali",
    country: "Indonesia",
    flag: "🇮🇩",
    image: "/images/travel/bali.jpg",
    activity: "🌴",
    activityLabel: "Island Life",
    description: "Lush emerald rice terraces, sacred sea temples, world-class surfing, and serene tropical atmosphere.",
    highlights: ["Ubud rice terraces", "Uluwatu cliff sunset", "Beachside retreats"],
    coordinates: "8.3405° S, 115.0920° E",
  },
  {
    id: "zagreb",
    city: "Zagreb",
    country: "Croatia",
    flag: "🇭🇷",
    image: "/images/travel/zagreb.jpg",
    activity: "🏛️",
    activityLabel: "Austro-Hungarian Charm",
    description: "A vibrant capital defined by historic Upper Town cobblestones, bustling street cafes, and classic Austro-Hungarian architecture.",
    highlights: ["St. Mark's Church", "Gornji Grad (Upper Town)", "Dolac Open-Air Market"],
    coordinates: "45.8150° N, 15.9819° E",
  },
  {
    id: "plitvice-lakes",
    city: "Plitvice Lakes",
    country: "Croatia",
    flag: "🇭🇷",
    image: "/images/travel/plitvice-lakes.jpg",
    activity: "🌊",
    activityLabel: "Cascading Lakes & Trails",
    description: "A natural wonderland of sixteen terraced lakes joined by waterfalls, winding wooden boardwalks, and lush canopy.",
    highlights: ["Veliki Slap Waterfall", "Lower Lakes Boardwalk", "Emerald Lake Kozjak"],
    coordinates: "44.8654° N, 15.6025° E",
  },
  {
    id: "rijeka",
    city: "Rijeka",
    country: "Croatia",
    flag: "🇭🇷",
    image: "/images/travel/rijeka.jpg",
    activity: "⚓",
    activityLabel: "Port City & Coast",
    description: "Croatia's principal port city, rich in maritime heritage, panoramic hilltop castle views, and lively pedestrian boulevards.",
    highlights: ["Trsat Castle view", "Korzo Promenade", "Kvarner Bay coast"],
    coordinates: "45.3271° N, 14.4422° E",
  },
  {
    id: "ljubljana",
    city: "Ljubljana",
    country: "Slovenia",
    flag: "🇸🇮",
    image: "/images/travel/ljubljana.jpg",
    activity: "🐉",
    activityLabel: "Riverside & Dragon Bridges",
    description: "An eco-green capital with car-free riverbanks, dragon legends, hilltop medieval castles, and effortless relaxed charm.",
    highlights: ["Dragon Bridge & Triple Bridge", "Ljubljana Castle hill", "Ljubljanica riverbank cafes"],
    coordinates: "46.0569° N, 14.5058° E",
  },
  {
    id: "lake-bled",
    city: "Lake Bled",
    country: "Slovenia",
    flag: "🇸🇮",
    image: "/images/travel/lake-bled.jpg",
    activity: "🚣",
    activityLabel: "Alpine Lake & Island",
    description: "A picture-postcard Julian Alps lake featuring a fairytale island church, cliffside castle, and iconic pletna boat rides.",
    highlights: ["Bled Island Pilgrimage Church", "Bled Castle cliff viewpoint", "Traditional Kremšnita cream cake"],
    coordinates: "46.3636° N, 14.0938° E",
  },
  {
    id: "villach",
    city: "Villach",
    country: "Austria",
    flag: "🇦🇹",
    image: "/images/travel/villach.jpg",
    activity: "🏔️",
    activityLabel: "Alpine Gateway",
    description: "A scenic Carinthian city nestled along the Drau River near the Alpine borders of Austria, Slovenia, and Italy.",
    highlights: ["Hauptplatz Historic Square", "Drau River promenade", "Dobratsch Nature Park views"],
    coordinates: "46.6111° N, 13.8558° E",
  },
  {
    id: "trieste",
    city: "Trieste",
    country: "Italy",
    flag: "🇮🇹",
    image: "/images/travel/trieste.jpg",
    activity: "☕",
    activityLabel: "Seafront Plaza & Coffee Culture",
    description: "An elegant Adriatic port city blending Italian style, Austrian literary coffeehouse traditions, and expansive seafront plazas.",
    highlights: ["Piazza Unità d'Italia", "Miramare Castle coast", "Canal Grande waterfront"],
    coordinates: "45.6495° N, 13.7768° E",
  },
  {
    id: "istanbul",
    city: "Istanbul",
    country: "Turkey",
    flag: "🇹🇷",
    image: "/images/travel/istanbul.jpg",
    activity: "🕌",
    activityLabel: "Bosphorus & Historic Minarets",
    description: "Where East meets West — a breathtaking metropolis of soaring minarets, ancient spice bazaars, and Bosphorus strait views.",
    highlights: ["Hagia Sophia & Blue Mosque", "Grand Bazaar spice alleys", "Bosphorus sunset ferry"],
    coordinates: "41.0082° N, 28.9784° E",
  },
  {
    id: "cappadocia",
    city: "Cappadocia",
    country: "Turkey",
    flag: "🇹🇷",
    image: "/images/travel/cappadocia.jpg",
    activity: "🎈",
    activityLabel: "Hot Air Balloons & Cave Dwellings",
    description: "A surreal landscape of fairy chimney rock formations, ancient cave dwellings, and sunrise hot air balloon flights.",
    highlights: ["Göreme Open Air Museum", "Sunrise hot air balloon flight", "Love Valley rock formations"],
    coordinates: "38.6431° N, 34.8289° E",
  },
  {
    id: "adana",
    city: "Adana",
    country: "Turkey",
    flag: "🇹🇷",
    image: "/images/travel/adana.jpg",
    activity: "🍢",
    activityLabel: "Culinary Heritage & Roman Bridge",
    description: "Southern culinary capital famous for authentic Adana kebab, ancient Roman Stone Bridge, and grand Seyhan riverfront.",
    highlights: ["Taşköprü (Stone Bridge)", "Sabancı Central Mosque", "Authentic Adana Kebap feast"],
    coordinates: "37.0000° N, 35.3213° E",
  },
  {
    id: "izmir",
    city: "Izmir",
    country: "Turkey",
    flag: "🇹🇷",
    image: "/images/travel/izmir.jpg",
    activity: "🌅",
    activityLabel: "Aegean Waterfront Promenade",
    description: "A laid-back Aegean coastal city boasting vibrant seaside promenades, historic clock towers, and Mediterranean energy.",
    highlights: ["Kordon waterfront promenade", "Saat Kulesi (Clock Tower)", "Kemeraltı historic market"],
    coordinates: "38.4237° N, 27.1428° E",
  },
  {
    id: "alanya",
    city: "Alanya",
    country: "Turkey",
    flag: "🇹🇷",
    image: "/images/travel/alanya.JPG",
    activity: "🏰",
    activityLabel: "Cliffside Fortress & Turquoise Bay",
    description: "A stunning Mediterranean resort town dominated by a dramatic medieval castle cliff, Cleopatra Beach, and turquoise waters.",
    highlights: ["Alanya Castle peninsula", "Red Tower (Kızıl Kule)", "Cleopatra Beach"],
    coordinates: "36.5438° N, 31.9998° E",
  },
  {
    id: "fethiye",
    city: "Fethiye",
    country: "Turkey",
    flag: "🇹🇷",
    image: "/images/travel/fethiye.jpg",
    activity: "🪂",
    activityLabel: "Turquoise Coast & Paragliding",
    description: "The heart of the Turkish Riviera, famed for the Ölüdeniz lagoon, Lycian rock tombs carved into cliffs, and world-class paragliding.",
    highlights: ["Ölüdeniz Blue Lagoon", "Lycian Rock Tombs", "Butterfly Valley boat trip"],
    coordinates: "36.6516° N, 29.1164° E",
  },
  {
    id: "ephesus",
    city: "Ephesus",
    country: "Turkey",
    flag: "🇹🇷",
    image: "/images/travel/ephesus.jpg",
    activity: "🏛️",
    activityLabel: "Ancient Greco-Roman Ruins",
    description: "One of the greatest preserved classical cities of the ancient world, featuring the majestic Library of Celsus and Great Theatre.",
    highlights: ["Library of Celsus facade", "The Great Theatre", "Marble Street & Terrace Houses"],
    coordinates: "37.9484° N, 27.3639° E",
  },
  {
    id: "cancun",
    city: "Cancún",
    country: "Mexico",
    flag: "🇲🇽",
    image: "/images/travel/cancun.jpg",
    activity: "🏖️",
    activityLabel: "Caribbean Coast & White Sands",
    description: "Pristine turquoise Caribbean waters, powdery white sand beaches, and vibrant coastal energy on the Yucatán Peninsula.",
    highlights: ["Playa Delfines coastal view", "Hotel Zone Caribbean beach", "Underwater Museum (MUSA)"],
    coordinates: "21.1619° N, 86.8515° W",
  },
  {
    id: "cenotes-dzitnup",
    city: "Cenotes Dzitnup",
    country: "Mexico",
    flag: "🇲🇽",
    image: "/images/travel/cenotes-dzitnup.jpg",
    activity: "🤿",
    activityLabel: "Subterranean Cenote Swimming",
    description: "Mystical subterranean limestone caverns illuminated by single sunbeams piercing through cave ceilings into crystal turquoise waters.",
    highlights: ["Cenote Samulá beam of light", "Cenote Xkekén stalactites", "Subterranean freshwater swim"],
    coordinates: "20.6596° N, 88.2435° W",
  },
  {
    id: "chichen-itza",
    city: "Chichén Itzá",
    country: "Mexico",
    flag: "🇲🇽",
    image: "/images/travel/chichen-itza.jpg",
    activity: "📐",
    activityLabel: "Mayan Pyramid & Wonder of the World",
    description: "The iconic ancient Mayan city featuring the towering Temple of Kukulcán, astronomical observatories, and rich archaeological history.",
    highlights: ["El Castillo (Temple of Kukulcán)", "Great Ball Court", "El Caracol Observatory"],
    coordinates: "20.6843° N, 88.5678° W",
  },
  {
    id: "merida",
    city: "Mérida",
    country: "Mexico",
    flag: "🇲🇽",
    image: "/images/travel/merida.jpg",
    activity: "🎨",
    activityLabel: "Yucatecan Culture & Pastel Plazas",
    description: "The 'White City' of Yucatán, renowned for pastel colonial architecture, vibrant evening plazas, and rich Yucatecan gastronomy.",
    highlights: ["Paseo de Montejo avenue", "Plaza Grande evening music", "Coqui Coqui & Yucatecan dishes"],
    coordinates: "20.9674° N, 89.5926° W",
  },
  {
    id: "cascadas-de-agua-azul",
    city: "Cascadas de Agua Azul",
    country: "Mexico",
    flag: "🇲🇽",
    image: "/images/travel/cascadas-de-agua-azul.jpg",
    activity: "🌊",
    activityLabel: "Jungle Waterfalls & Turquoise Pools",
    description: "A breathtaking series of turquoise-blue waterfalls cascading through lush Chiapas jungle, forming natural limestone swimming pools.",
    highlights: ["Turquoise water cascades", "Jungle canopy hiking trails", "Natural limestone pools"],
    coordinates: "17.2581° N, 92.1153° W",
  },
  {
    id: "calakmul",
    city: "Calakmul",
    country: "Mexico",
    flag: "🇲🇽",
    image: "/images/travel/calakmul.jpg",
    activity: "🐆",
    activityLabel: "Deep Jungle Ruins",
    description: "An ancient Mayan superpower hidden deep within a UNESCO biosphere reserve, where giant pyramids rise above endless rainforest canopy.",
    highlights: ["Great Pyramid Structure II climb", "Jungle biosphere wildlife", "Rainforest canopy vistas"],
    coordinates: "18.1058° N, 89.8105° W",
  },
  {
    id: "playa-del-carmen",
    city: "Playa del Carmen",
    country: "Mexico",
    flag: "🇲🇽",
    image: "/images/travel/playa-del-carmen.jpg",
    activity: "🌴",
    activityLabel: "Riviera Maya Beach Town",
    description: "A lively Riviera Maya coastal destination known for its pedestrian Fifth Avenue, beach clubs, and easy access to coastal reefs.",
    highlights: ["Quinta Avenida pedestrian strip", "Playa Mamitas beach vibe", "Cozy beachfront cafes"],
    coordinates: "20.6296° N, 87.0739° W",
  },
  {
    id: "taipei",
    city: "Taipei",
    country: "Taiwan",
    flag: "🇹🇼",
    image: "/images/travel/taipei.jpg",
    activity: "🗼",
    activityLabel: "Night Markets & Tower Views",
    description: "A vibrant capital of neon night markets, world-famous street food, tea houses, and towering modern architecture.",
    highlights: ["Taipei 101 observatory", "Raohe Night Market street food", "Elephant Mountain sunset"],
    coordinates: "25.0330° N, 121.5654° E",
  },
  {
    id: "taichung",
    city: "Taichung",
    country: "Taiwan",
    flag: "🇹🇼",
    image: "/images/travel/taichung.jpg",
    activity: "🍵",
    activityLabel: "Cultural Heart & Bubble Tea",
    description: "The birthplace of boba tea, celebrated for art spaces, sprawling night markets, and pleasant coastal breezes.",
    highlights: ["Fengjia Night Market", "Miyahara confectionery castle", "National Taichung Theater"],
    coordinates: "24.1477° N, 120.6736° E",
  },
  {
    id: "hanoi",
    city: "Hanoi",
    country: "Vietnam",
    flag: "🇻🇳",
    image: "/images/travel/hanoi.jpg",
    activity: "☕",
    activityLabel: "Old Quarter & Egg Coffee",
    description: "A thousand-year-old capital brimming with French colonial heritage, bustling Old Quarter alleys, and legendary egg coffee.",
    highlights: ["Hoan Kiem Lake & Red Bridge", "Old Quarter street food", "Train Street cafes"],
    coordinates: "21.0285° N, 105.8542° E",
  },
  {
    id: "ha-long-bay",
    city: "Ha Long Bay",
    country: "Vietnam",
    flag: "🇻🇳",
    image: "/images/travel/ha-long-bay.jpg",
    activity: "⛵",
    activityLabel: "Emerald Waters & Karsts",
    description: "A UNESCO wonder of thousands of towering limestone karsts and islets emerging dramatically from emerald waters.",
    highlights: ["Overnight boat cruise", "Sung Sot (Surprise) Cave", "Kayaking through hidden lagoons"],
    coordinates: "20.9101° N, 107.1839° E",
  },
  {
    id: "sa-pa",
    city: "Sa Pa",
    country: "Vietnam",
    flag: "🇻🇳",
    image: "/images/travel/sa-pa.jpg",
    activity: "🏔️",
    activityLabel: "Mist-Veiled Rice Terraces",
    description: "Highland mountain retreat nestled among mist-shrouded valleys, cascading terraced rice fields, and ethnic tribal villages.",
    highlights: ["Fansipan Peak summit (Indochina Roof)", "Muong Hoa Valley trekking", "Cat Cat village culture"],
    coordinates: "22.3364° N, 103.8438° E",
  },
  {
    id: "bangkok",
    city: "Bangkok",
    country: "Thailand",
    flag: "🇹🇭",
    image: "/images/travel/bangkok.jpg",
    activity: "🛺",
    activityLabel: "Golden Temples & Street Eats",
    description: "An exhilarating capital of ornate golden spires, aromatic street food stalls, tuk-tuk rides, and Chao Phraya river life.",
    highlights: ["Grand Palace & Wat Phra Kaew", "Wat Arun riverfront temple", "Yaowarat Road (Chinatown) eats"],
    coordinates: "13.7563° N, 100.5018° E",
  },
  {
    id: "hua-hin",
    city: "Hua Hin",
    country: "Thailand",
    flag: "🇹🇭",
    image: "/images/travel/hua-hin.jpg",
    activity: "🏖️",
    activityLabel: "Royal Beachside Resort",
    description: "A classic seaside resort town famed for royal summer palaces, serene sandy beaches, and fresh seafood markets.",
    highlights: ["Phraya Nakhon Cave pavilion", "Hua Hin Railway Station", "Cicada Night Market"],
    coordinates: "12.5684° N, 99.9577° E",
  },
  {
    id: "kuala-lumpur",
    city: "Kuala Lumpur",
    country: "Malaysia",
    flag: "🇲🇾",
    image: "/images/travel/kuala-lumpur.jpg",
    activity: "🏙️",
    activityLabel: "Petronas Towers & Batu Caves",
    description: "A soaring multicultural metropolis dominated by the iconic twin towers, vibrant street markets, and colorful rainbow steps.",
    highlights: ["Petronas Twin Towers skybridge", "Batu Caves rainbow staircase", "Jalan Alor food street"],
    coordinates: "3.1390° N, 101.6869° E",
  },
  {
    id: "fairbanks",
    city: "Fairbanks",
    country: "United States",
    flag: "🇺🇸",
    image: "/images/travel/fairbanks.jpg",
    activity: "🌌",
    activityLabel: "Northern Lights & Arctic Wilderness",
    description: "Golden Heart of Alaska, famous for dancing Aurora Borealis, arctic wilderness, and hot spring retreats.",
    highlights: ["Aurora Borealis hunting", "Chena Hot Springs", "Denali wilderness gateway"],
    coordinates: "64.8401° N, 147.7200° W",
  },
  {
    id: "miami",
    city: "Miami",
    country: "United States",
    flag: "🇺🇸",
    image: "/images/travel/miami.jpg",
    activity: "🌴",
    activityLabel: "Art Deco & South Beach",
    description: "Sun-soaked coastal metropolis blending Art Deco architecture, South Beach energy, and vibrant Latin American culture.",
    highlights: ["Ocean Drive & South Beach", "Wynwood Walls street art", "Little Havana Cuban eats"],
    coordinates: "25.7617° N, 80.1918° W",
  },
  {
    id: "seattle",
    city: "Seattle",
    country: "United States",
    flag: "🇺🇸",
    image: "/images/travel/seattle.jpg",
    activity: "☕",
    activityLabel: "Emerald City Skyline & Coffee",
    description: "The Emerald City, surrounded by water and evergreen forests, famed for the Space Needle and artisanal coffee culture.",
    highlights: ["Pike Place Market", "Space Needle panorama", "Elliott Bay waterfront"],
    coordinates: "47.6062° N, 122.3321° W",
  },
  {
    id: "san-francisco",
    city: "San Francisco",
    country: "United States",
    flag: "🇺🇸",
    image: "/images/travel/san-francisco.jpg",
    activity: "🌉",
    activityLabel: "Golden Gate & Cable Cars",
    description: "Iconic fog-kissed peninsula city of steep rolling hills, historic cable cars, and the majestic Golden Gate Bridge.",
    highlights: ["Golden Gate Bridge walk", "Fisherman's Wharf & Pier 39", "Historic cable car rides"],
    coordinates: "37.7749° N, 122.4194° W",
  },
  {
    id: "new-york",
    city: "New York",
    country: "United States",
    flag: "🇺🇸",
    image: "/images/travel/new-york.jpg",
    activity: "🗽",
    activityLabel: "Metropolis Skyline & Broadway",
    description: "The city that never sleeps — iconic skyscrapers, sprawling Central Park strolls, Broadway lights, and endless energy.",
    highlights: ["Central Park & Fifth Avenue", "Brooklyn Bridge stroll", "Times Square & Broadway"],
    coordinates: "40.7128° N, 74.0060° W",
  },
  {
    id: "washington-dc",
    city: "Washington, D.C.",
    country: "United States",
    flag: "🇺🇸",
    image: "/images/travel/washington-dc.jpg",
    activity: "🏛️",
    activityLabel: "Monuments & Museums",
    description: "The nation's capital, defined by grand neoclassical monuments, the National Mall, and world-class Smithsonian museums.",
    highlights: ["National Mall & Lincoln Memorial", "Smithsonian Museums", "U.S. Capitol Building"],
    coordinates: "38.9072° N, 77.0369° W",
  },
  {
    id: "newport",
    city: "Newport",
    country: "United States",
    flag: "🇺🇸",
    image: "/images/travel/newport.jpg",
    activity: "⛵",
    activityLabel: "Gilded Age Mansions & Coast",
    description: "Historic Rhode Island coastal haven famous for opulent Gilded Age mansions, ocean Cliff Walk, and sailing culture.",
    highlights: ["The Breakers mansion tour", "Newport Cliff Walk", "Ocean Drive scenic coast"],
    coordinates: "41.4901° N, 71.3128° W",
  },
  {
    id: "pittsburgh",
    city: "Pittsburgh",
    country: "United States",
    flag: "🇺🇸",
    image: "/images/travel/pittsburgh.jpg",
    activity: "🌁",
    activityLabel: "Three Rivers & Yellow Bridges",
    description: "The Steel City, transformed into a vibrant cultural hub defined by three merging rivers, historic funicular inclines, and iconic bridges.",
    highlights: ["Duquesne Incline Mount Washington view", "Three Rivers confluence", "Andy Warhol Museum"],
    coordinates: "40.4406° N, 79.9959° W",
  },
  {
    id: "mauritius",
    city: "Mauritius",
    country: "Mauritius",
    flag: "🇲🇺",
    image: "/images/travel/mauritius.jpg",
    activity: "🏝️",
    activityLabel: "Indian Ocean Lagoons & Coral Reefs",
    description: "An island paradise of turquoise lagoons, volcanic peaks, botanical gardens, and pristine Indian Ocean beaches.",
    highlights: ["Le Morne Brabant peak view", "Trou aux Biches lagoon", "Sir Seewoosagur Ramgoolam Botanic Garden"],
    coordinates: "20.3484° S, 57.5522° E",
  },
  {
    id: "cape-town",
    city: "Cape Town",
    country: "South Africa",
    flag: "🇿🇦",
    image: "/images/travel/cape-town.jpg",
    activity: "⛰️",
    activityLabel: "Table Mountain & Coastal Drives",
    description: "Where dramatic mountain peaks meet two oceans — iconic Table Mountain aerials, penguin beaches, and scenic coastal drives.",
    highlights: ["Table Mountain aerial cableway", "Cape of Good Hope scenic drive", "Boulders Beach penguin colony"],
    coordinates: "33.9249° S, 18.4241° E",
  },
  {
    id: "paris",
    city: "Paris",
    country: "France",
    flag: "🇫🇷",
    image: "/images/travel/paris.jpg",
    activity: "🗼",
    activityLabel: "City of Lights & Grand Boulevards",
    description: "The City of Light — iconic Eiffel Tower illuminations, Haussmann boulevards, world-renowned museums, and sidewalk bistros.",
    highlights: ["Eiffel Tower at dusk", "Louvre Museum masterpieces", "Seine riverbank strolls"],
    coordinates: "48.8566° N, 2.3522° E",
  },
  {
    id: "venice",
    city: "Venice",
    country: "Italy",
    flag: "🇮🇹",
    image: "/images/travel/venice.jpg",
    activity: "🛶",
    activityLabel: "Grand Canal & Gondolas",
    description: "The Floating City of labyrinthine canals, ornate marble palaces, historic gondola rides, and Saint Mark's Square.",
    highlights: ["Grand Canal gondola ride", "St. Mark's Basilica & Campanile", "Rialto Bridge panoramas"],
    coordinates: "45.4408° N, 12.3155° E",
  },
  {
    id: "rome",
    city: "Rome",
    country: "Italy",
    flag: "🇮🇹",
    image: "/images/travel/rome.jpg",
    activity: "🏛️",
    activityLabel: "Eternal City & Colosseum",
    description: "The Eternal City — millennial history around every corner, ancient amphitheatres, Trevi Fountain wishes, and piazza gelatos.",
    highlights: ["Colosseum & Roman Forum", "Pantheon & Trevi Fountain", "Vatican City & Sistine Chapel"],
    coordinates: "41.9028° N, 12.4964° E",
  },
  {
    id: "pisa",
    city: "Pisa",
    country: "Italy",
    flag: "🇮🇹",
    image: "/images/travel/pisa.jpg",
    activity: "📐",
    activityLabel: "Leaning Tower & Miracle Square",
    description: "Tuscan city famed worldwide for the white marble Leaning Tower on the green lawns of Piazza dei Miracoli.",
    highlights: ["Leaning Tower of Pisa", "Pisa Cathedral (Duomo)", "Piazza dei Miracoli lawn"],
    coordinates: "43.7228° N, 10.4017° E",
  },
  {
    id: "florence",
    city: "Florence",
    country: "Italy",
    flag: "🇮🇹",
    image: "/images/travel/florence.jpg",
    activity: "🎨",
    activityLabel: "Renaissance Masterpieces",
    description: "Cradle of the Renaissance — Brunelleschi's iconic Duomo dome, Michelangelo's David, and golden Arno river sunsets.",
    highlights: ["Florence Cathedral (Duomo)", "Ponte Vecchio Bridge sunset", "Uffizi Gallery Renaissance art"],
    coordinates: "43.7696° N, 11.2558° E",
  },
  {
    id: "zurich",
    city: "Zurich",
    country: "Switzerland",
    flag: "🇨🇭",
    image: "/images/travel/zurich.jpg",
    activity: "🏔️",
    activityLabel: "Lakeside Elegance & Old Town",
    description: "A pristine global financial hub where Lake Zurich's clear waters border medieval guild houses and alpine views.",
    highlights: ["Lake Zurich promenade", "Altstadt (Old Town) cobbles", "Bahnhofstrasse shopping"],
    coordinates: "47.3769° N, 8.5417° E",
  },
  {
    id: "interlaken",
    city: "Interlaken",
    country: "Switzerland",
    flag: "🇨🇭",
    image: "/images/travel/interlaken.jpg",
    activity: "🏔️",
    activityLabel: "Alpine Adventure Capital",
    description: "Nestled between Lake Thun and Lake Brienz beneath the Eiger, Mönch, and Jungfrau peaks — Switzerland's adventure heartland.",
    highlights: ["Jungfraujoch (Top of Europe)", "Harder Kulm panoramic viewpoint", "Lakes Thun & Brienz cruises"],
    coordinates: "46.6863° N, 7.8632° E",
  },
  {
    id: "geneva",
    city: "Geneva",
    country: "Switzerland",
    flag: "🇨🇭",
    image: "/images/travel/geneva.jpg",
    activity: "🌊",
    activityLabel: "Lake Fountain & Diplomacy",
    description: "A global diplomatic capital framed by Lake Geneva's towering Jet d'Eau fountain and distant snow-capped Mont Blanc.",
    highlights: ["Jet d'Eau water fountain", "Palais des Nations", "Lake Geneva promenade"],
    coordinates: "46.2044° N, 6.1432° E",
  },
  {
    id: "manila",
    city: "Manila",
    country: "Philippines",
    flag: "🇵🇭",
    image: "/images/travel/manila.jpg",
    activity: "🌇",
    activityLabel: "Historic Walled City & Bay Sunsets",
    description: "Bustling capital of Spanish colonial walled heritage at Intramuros, sunset baywalk views, and warm Filipino hospitality.",
    highlights: ["Intramuros Spanish walled city", "Manila Bay sunset boardwalk", "Fort Santiago history"],
    coordinates: "14.5995° N, 120.9842° E",
  },
  {
    id: "seoul",
    city: "Seoul",
    country: "South Korea",
    flag: "🇰🇷",
    image: "/images/travel/seoul.jpg",
    activity: "🏯",
    activityLabel: "Royal Palaces & K-Culture",
    description: "A dynamic metropolis where centuries-old royal palaces sit in harmony with futuristic digital skyscrapers and K-pop culture.",
    highlights: ["Gyeongbokgung Palace & Hanbok", "Bukchon Hanok Village", "N Seoul Tower & Myeongdong"],
    coordinates: "37.5665° N, 126.9780° E",
  },
  {
    id: "dubai",
    city: "Dubai",
    country: "United Arab Emirates",
    flag: "🇦🇪",
    image: "/images/travel/dubai.jpg",
    activity: "🏙️",
    activityLabel: "Futuristic Towers & Desert Dunes",
    description: "A futuristic desert oasis of record-breaking skyscrapers, palm-shaped archipelagos, luxury shopping, and golden dunes.",
    highlights: ["Burj Khalifa observatory", "Dubai Mall & Fountain show", "Desert safari dune bashing"],
    coordinates: "25.2048° N, 55.2708° E",
  },
];
